language: node_js
dist: trusty
sudo: required
node_js: "8"
script:
- npm run build
- npm test
cache:
  directories:
  - node_modules
env:
  global:
  - BX_APP=watson-conversation-duo-dev
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
  - B_DOMAIN=ng.bluemix.net
before_deploy:
- npm install -g bx-blue-green
deploy:
- provider: script
  script: bx-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/assistant-demo
  skip_cleanup: true
- provider: script
  script: BX_APP=watson-conversation-duo-test bx-blue-green-travis
  on:
    branch: dev
    repo: watson-developer-cloud/assistant-demo
  skip_cleanup: true
